import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chaostreff Osnabrück e.V. - Pressemitteilung osna.social",
  // TODO: Add description
  // description: "Generated by create next app",
};

export default async function PmMastodon() {
  return <PmMastodonDe />;
}

const PmMastodonDe = () => {
  metadata.title = "Chaostreff Osnabrück e.V. - Rechtliche Hinweise";
  return (
    <div className="prose dark:prose-invert">
      <h1>Pressemitteilung</h1>
      <h2>
        Dezentrales und datensparsames soziales Netzwerk osna.social eröffnet
        Donnerstag
      </h2>
      Am Donnerstag, den 19.11. wird der Chaostreff Osnabrück e.V. das soziale
      Netzwerk und Plattform osna.social für alle Bürger:innen online schalten.
      Dies soll ein Ort werden, an dem sich Menschen aus Osnabrück und dem
      Osnabrücker Land unterhalten, diskutieren und austauschen können. Den
      Fokus setzt der Verein dabei auf Datensparsamkeit und Dezentralität.
      <br />
      <br />
      &quot;Hier werden die Daten der Nutzer:innen nicht verkauft oder in
      Algorithmen gesteckt, um die beste Werbung anzuzeigen. Die Nutzer:innen
      bleiben vollkommen anonym und ihre Daten sind sicher auf den in Osnabrück
      betriebenen Servern unseres Vereins.&quot; sagt Marvin Wilke,
      Administrator und Vereinsmitglied beim Chaostreff.
      <br />
      <br />
      Die ersten Schritte hat das soziale Netz beim diesjährigen Hackathon der
      Stadtwerke Osnahack auf sich genommen. Dort hat das Team OsnaHub, welches
      zum Großteil aus Mitgliedern des Chaostreffs bestand, die Plattform
      eingerichtet, das Design angepasst und vor allem die Plattform mit
      Inhalten aus der Region versorgt. So werden beispielsweise viele
      Informationen von Institutionen in und um Osnabrück aggregiert und
      automatisiert in das Netzwerk eingespeist. Zudem hat das Team gezeigt, wie
      die Daten aus der Plattform wiederum genutzt und aufbereitet werden können
      um ein Dashboard zur Bürger:innenbeteiligung zu erstellen. Mit der Idee
      hat das Team den dritten Platz beim Osnahack belegt.
      <br />
      <br />
      Wie auch bei Twitter können Nutzer:innen auf osna.social Profile
      erstellen, Nachrichten, Bilder und Videos teilen. Dabei sind die
      Textnachrichten ähnlich wie bei Twitter auf 500 Zeichen begrenzt.
      osna.social nutzt dafür die Freie Software Mastodon (Open Source), ein
      dezentrales soziales Netzwerk. Es gibt hiervon bereits viele Instanzen,
      die von verschiedenen Personen, Vereinen oder Firmen betrieben werden und
      untereinander vernetzt sind. Nutzer:innen von osna.social können so unter
      anderem Nutzer:innen von ruhr.social, einem Mastodonserver bzw. einer
      Instanz aus dem Ruhrgebiet, folgen und Nachrichten austauschen. Damit sich
      alle Nutzer:innen auf der Plattform wohlfühlen, gibt es klare Community
      Regeln, welche beispielsweise jegliche Formen von Rassismus,
      Diskriminierung und Mobbing ablehnt.
      <br />
      <br />
      &quot;Wer bereits einen Mastodon Account auf einer anderen Instanz hat,
      kann übrigens seine Daten auf unsere Instanz umziehen. So kann, wer will,
      seiner Heimatstadt etwas näher sein und die Freiheit seiner Daten
      praktizieren&quot;, ergänzt Hannes Janott, Mitglied im Chaostreff.
      <br />
      <br />
      osna.social wird von Ehrenamtlichen betrieben, das Projekt trägt sich aus
      den Mitteln des Vereins und es bestehen keine Interessen Geld mit der
      Plattform zu verdienen. Aus diesem Grund werden keine IP-Adressen
      gespeichert, keine Daten an Dritte weitergegeben und keine Werbung
      geschaltet. Die Nutzung ist für alle Interessierten kostenlos.
      <br />
      <br />
      Die Registrierung ist ab Donnerstag unter{" "}
      <a href="https://osna.social">osna.social</a> eröffnet.
      <br />
      <br />
      Weitere Informationen, die erläutern, wie Mastodon funktioniert und wer es
      benutzt:
      <ul>
        <li>
          <a href="https://heise.de/-3675432" rel="noreferer" target="_blank">
            Heise: &quot;Dezentral und Open Source: Ist Mastodon das bessere
            Twitter?&quot;
          </a>
        </li>
        <li>
          <a
            href="https://www.vice.com/en/article/783akg/mastodon-is-like-twitter-without-nazis-so-why-are-we-not-using-it"
            rel="noreferer"
            target="_blank"
          >
            Vice: &quot;Mastodon Is Like Twitter Without Nazis, So Why Are We
            Not Using It?&quot;
          </a>
        </li>
        <li>
          <a
            href="https://www.youtube.com/watch?v=IPSbNdBmWKE"
            rel="noreferer"
            target="_blank"
          >
            Youtube Video: &quot;Was ist Mastodon?&quot;
          </a>
        </li>
        <li>
          <a
            href="https://www.behoerden-spiegel.de/2020/03/05/twitter-alternative-fuer-behoerden/"
            rel="noreferer"
            target="_blank"
          >
            Behörden Spiegel: &quot;Twitter-Alternative für Behörden&quot;
          </a>
        </li>
        <li>
          <a
            href="https://www.behoerden-spiegel.de/2020/10/13/bfdi-startet-alternativen-social-media-kanal/"
            rel="noreferer"
            target="_blank"
          >
            Behörden Spiegel: &quot;BfDI startet alternativen
            Social-Media-Kanal&quot;
          </a>
        </li>
      </ul>
    </div>
  );
};
