import type { Metadata } from "next";
import "./../globals.css";
import { ThemeProvider } from "next-themes";
import { languages } from "../i18n/settings";
import Image from "next/image";
import CTreffLogo from "../../public/ctreffos-logo.png";
import Link from "next/link";
import { getTranslation } from "../i18n";

export const metadata: Metadata = {
  title: "Chaostreff Osnabrück e.V.",
  // TODO: Add description
  // description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const paramsAwaited = await params;

  const dict = await getTranslation(paramsAwaited.lang);

  return (
    <html lang={paramsAwaited.lang} suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider attribute="class">
          <div className="min-h-screen flex justify-center">
            <div className="flex flex-col min-h-screen">
              <Link href={`/${paramsAwaited.lang}`}>
                <header className="flex flex-col items-center sm:items-start pb-6">
                  <Image
                    src={CTreffLogo}
                    alt="Chaostreff Osnabrück Logo"
                    className="invert-0 dark:invert"
                  />
                </header>
              </Link>
              <main className="flex flex-col gap-8 md:max-w-2xl row-start-2 items-center sm:items-start">
                {children}
              </main>
              <footer className="flex flex-col gap-3 py-8">
                <hr />
                <div className="flex flex-col sm:flex-row gap-8 items-center sm:items-start">
                  <Link href={`/${paramsAwaited.lang}`}>{dict.home}</Link>
                  <Link href={`/${paramsAwaited.lang}/site-notice`}>
                    {dict["site-notice"]}
                  </Link>
                  <Link href={`/${paramsAwaited.lang}/privacy-policy`}>
                    {dict["privacy-policy"]}
                  </Link>
                  <Link href={`/${paramsAwaited.lang}/legal-notice`}>
                    {dict["legal-notice"]}
                  </Link>
                  <Link href={`/${paramsAwaited.lang}/donate`}>
                    {dict.donate}
                  </Link>
                </div>

                <div className="flex gap-6 justify-center">
                  <Link href="/de">Deutsch</Link>
                  <Link href="/en">English</Link>
                </div>
              </footer>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
